
get http://localhost:3000/

###
get http://localhost:3000/hello

###
get http://localhost:3000/world

###
get http://localhost:3000/api/exercises/10/words

###
get http://localhost:3000/api/locations/9
###
delete http://localhost:3000/api/words/3

###
post http://localhost:3000/api/words/
content-type: application/json

{ "original": "Dog", "translated": "Koira","language": "EN" }

###
get http://localhost:3000/api/points

###

post http://localhost:3000/api/points/
content-type: application/json

{ "exercise_name": "EX 01", "points": "11","max_points": "15","user_id": "1" }

###
get http://localhost:3000/api/points/EXERCISE%2001%20-%20BASIC%20WORDS/1 

###

post http://localhost:3000/api/auth/login
content-type: application/json

{ "name": "Liisa", "password": "4nr!j_i9" }